version: "3"

services:
  development:
    image: postgres:11-alpine
    ports:
      - 35432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  test:
    image: postgres:11-alpine
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
