version: "3"

services:
  development:
    image: postgres:11-alpine
    ports:
      - 35432:5432
    # volumes:
    # - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  test:
    image: postgres:11-alpine
    ports:
      - 54320:5432
    # volumes:
    # - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
# volumes:
#   postgres_data:
#     driver: local
